- name: Download da instalação wordpress
  get_url:
    url: https://www.wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz

- name: Descompacta o wordpress
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /var/www/
    remote_src: yes
  become: yes

- name: Copia arquivo de configuração do wordpress
  copy:
    src: /var/www/wordpress/wp-config-sample.php
    dest: /var/www/wordpress/wp-config.php
    remote_src: true
  become: true

- name: Configura o wordpress para acessar o banco de dados
  replace:
    path: /var/www/wordpress/wp-config.php
    regexp: "{{ item.regex }}"
    replace: "{{ item.value }}"
  with_items:
    - { regex: 'database_name_here', value: "{{ wp_db_name }}" }
    - { regex: 'username_here', value: "{{ wp_username }}" }
    - { regex: 'password_here', value: "{{ wp_user_password }}" }
  become: true

# - name: Configura apache para servir wordpress
#   copy:
#     src: files/000-default.conf
#     dest: /etc/apache2/sites-available/000-default.conf
#   become: yes
#   notify: 
#     - reinicia apache

- name: Configura apache para servir wordpress
  template:
    src: templates/000-default.conf.j2
    dest: /etc/apache2/sites-available/000-default.conf
  become: yes
  notify: 
    - reinicia apache